### ISSUE TITLE
Small comment on interface design in eventlist, not required, but may be nice

### ISSUE THREAD

**Issue by Outfenneced** [jnick1/mesa#21]
When shrinking the horizontal size on the event list, it seems to collapse down in a weird way. I feel like the description field should collapse down more when the horizontal size decreases instead of just wrapping with the name of the event.

**Comment by jnick1** [comment]
The styling for the table is rather funky to work with due to how overflow is handled in CSS. I've changed it as much as I can so that it improves, but it could still use improvement. However, for all intents and purposes, we'll consider this issue closed.
