### ISSUE TITLE
Overwriting blCalendar when user is part of multiple events

### ISSUE THREAD

**Issue by jnick1** [jnick1/mesa#25]
@Outfenneced 
Currently, when a user's calendar is retrieved, it is saved under the user's account. However, if the user has been included as an attendee for two separate events - especially ones which require different calendars, or events that occur at different times - saving blCalendar the second time will overwrite the calendar data to be used in the first event.

To solve this problem, I'd like to add another table to the database which references pkUserid in tblusers, pkEventid in tblevents, and contains the blCalendar field. The blCalendar field would be removed from tblusers and effectively moved to this new table. In this system, calendar data would be associated with both a user, and the event that the user has saved the calendar data for. This change will affect both services and algorithm code.

I do not want to change this much database structure now, but we'll do it at our next meeting on Monday.

**Comment by Outfenneced** [comment]
Huh, thought you could assign more than one person, my bad. I'll think on implementation until our next meeting. Shouldn't be too hard.

**Comment by jnick1** [comment]
Also, I've found out that the current max size of blCalendars is WAY too small. With events that only have a search width of about 2 weeks, I can use up to around 16KiB, with only a small amount of calendars. If we're searching up to 31 years, we're going to need to bump up the max size of that field. This is trivial to do, but I wanted to mention it here as it relates to blCalendar.
