### ISSUE TITLE
User authentication required for references access

### ISSUE THREAD

**Issue by Outfenneced** [jnick1/mesa#5]
While adding my references to the references.php page, I realized during checking that you need to be logged in to view it, which I don't think should be necessary. Looks like all that needs to be changed is to remove the if block starting here: https://github.com/jnick1/mesa/blob/master/includes/references.php#L23

**Comment by jnick1** [comment]
Fixed! The latest update to Interface changes this so that the sign-in button is located in the header, and not index.php. Because of this (along with a a few other changes), we can now allow the user to sign-in on any page we wish (instead of only index.php).
