### ISSUE TITLE
Upon attempting to view found solutions, error received

### ISSUE THREAD

**Issue by Outfenneced** [jnick1/mesa#51]
I fixed the python thing and decided to try out the final product, but I received an error while finding times:
"Warning: Invalid argument supplied for foreach() in C:\wamp\www\mesa\includes\newevent.php on line 1180"

I keep receiving this in my testing, I'm unsure why or how or even if it's just me, but it's definitely an error. I get it in the frame that pops up to select an event time.

**Comment by jnick1** [comment]
If you check in the database under blOptiSuggestion, you may notice that the size of the blob is around 41 bytes (if you're getting the same error I got). Upon opening the blob, you'll find that the error, "no module named "classes" found" was raised. To solve this, rename Classes.py to classes.py. Also be sure to click the re-run button in FIND TIMES to reset the blob, or go into the database and manually set it to null.
